version: "3"
services:
  app_react:
    build: ./frontend
    container_name: app_react
    ports: 
     - 3000:3000
    depends_on:
      - app_node

  banco:
    image: postgres:13
    container_name: banco
    ports:
      - 2345:5432
    env_file:
      - ./node/.env
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_node:
    build: ./node
    container_name: app_node
    ports:
      - 5000:5000
    env_file:
      - ./node/.env
    volumes:
      - ./node:/usr/src
      - ./node/node_modules:/usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 40s docker-entrypoint.sh
    command: "npm run start"
    depends_on:
      - banco

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_react

volumes:
  volume_banco:
